#ifndef QTBLUEVIASDK_GLOBAL_H
#define QTBLUEVIASDK_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTBLUEVIASDK_LIBRARY)
#  define QTBLUEVIASDKSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTBLUEVIASDKSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTBLUEVIASDK_GLOBAL_H
